name: weather_project
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  intl: ^0.20.2
  geolocator: ^14.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

  retrofit_generator: ^9.2.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/



